[package]
name = "binja-luau"
version = "0.8.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
binaryninja = { git = "https://github.com/Vector35/binaryninja-api.git", branch = "master" }
num_enum = "0.5.7"
