[package]
name = "luaurch"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
binaryninja = { git = "https://github.com/Vector35/binaryninja-api.git", branch = "master" }
chumsky = "0.8.0"
num_enum = "0.5.7"
